"use client"
import type { Metadata } from "next";
import "./globals.css";
import { usePathname } from "next/navigation";
import { Providers } from "./Provider";
import Header from "$/components/generalcommponents/header";
import Footer from "$/components/generalcommponents/footer";
import Link from "next/link";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname=usePathname();

  const excludedpath=["/auth/login","/auth/signup", "/dashboard","/dashboard/upload","/dashboard/watch","/dashboard/edit"]

  const allowedPath=!excludedpath.includes(pathname);


  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* Other meta tags, title, etc. */}
        <title>MINI-com</title>
      </head>
      <body>
        <div className=" bg-transparent mx-auto  ">
          <Providers>
          {
            allowedPath &&  <Header />
          }
  
            <main>
              {children}
            </main>
          </Providers>
          {
            allowedPath && <Footer/>
          }
        </div>
      </body>
    </html>
  );
}
